### ISSUE TITLE
Change color after typing?

### ISSUE THREAD

**Issue by Yerdesha** [WetTortoise/gachiPRIDE-rainbow-username-in-twitch-#3]
Right now color changes at a time interval. Wouldn't it be more efficient changing it after you type in chat? Just an idea :)

**Comment by WetTortoise** [comment]
While I do believe it would be nice to have that option, you would need to join whatever channel you want to change your colour in making it not rainbow globally.  I might however improve this code in the future to improve more options so this may be possible, but for now this has already been done by the user @notnotquinn  https://github.com/NotNotQuinn/twitch-chat-colorchanger

**Comment by Yerdesha** [comment]
Do you mean the program would have to track the channel you type in? I'm not a programmer but can't that be done easily? Of course, I wouldn't know. But thank you for sharing the color changer by another user.
